[project]
name = "mastering-gui-programming-with-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.6"
dependencies = [
    "pyinstaller==3.4",
    "pyqt5>=5.15.11",
    "setuptools==41.0.1",
]
